# Generated by Django 2.2.2 on 2019-06-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Summary',
        ),
        migrations.AddField(
            model_name='article',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='Write a content'),
        ),
    ]
