# Generated by Django 2.2.2 on 2019-06-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Summary', models.TextField(default='Nada')),
                ('Soldout', models.BooleanField()),
            ],
        ),
    ]
